# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pomodoro < Formula
  desc "Pomodoro timer for nerds"
  homepage "https://neonxp.ru/pomodoro/"
  version "0.0.1"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.arm?
      url "http://github.com/neonxp/pomodoro/releases/download/v0.0.1/pomodoro_0.0.1_Darwin_arm64.tar.gz"
      sha256 "3e8b627ef05d2157364354817fb0f6a1ec08d9d0eaa17bab89e2ddd018120b90"

      def install
        bin.install "pomodoro"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/neonxp/pomodoro/releases/download/v0.0.1/pomodoro_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "38cb3d5edfa22ad7bec7a3316a07c0e3e3ec67efb896b2fa4ecdb3c8f773c705"

      def install
        bin.install "pomodoro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "http://github.com/neonxp/pomodoro/releases/download/v0.0.1/pomodoro_0.0.1_Linux_x86_64.tar.gz"
      sha256 "52aa9d4c4d78113063b113529d5254b8f6933d5c4effee799b40d59deff71637"

      def install
        bin.install "pomodoro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/neonxp/pomodoro/releases/download/v0.0.1/pomodoro_0.0.1_Linux_arm64.tar.gz"
      sha256 "3832dffaadf315ba24088b0f86c175127ea43d7c3952742e285a5e46a88bdfb8"

      def install
        bin.install "pomodoro"
      end
    end
  end
end
