# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Track < Formula
  desc "Time tracker for nerds"
  homepage "https://neonxp.ru/track/"
  version "0.0.1"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.arm?
      url "http://github.com/neonxp/track/releases/v0.0.1/track_0.0.1_Darwin_arm64.tar.gz"
      sha256 "8cc569510f3207cebc12ac2b5e301fc806cc764b7d967f10875d2bde85193911"

      def install
        bin.install "track"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/neonxp/track/releases/v0.0.1/track_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "f04a63bd99b5e30ab4fb63556b72c9fa292264d22732f90d572d9fd80d61fcac"

      def install
        bin.install "track"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/neonxp/track/releases/v0.0.1/track_0.0.1_Linux_arm64.tar.gz"
      sha256 "20d878d27ea89c6c9fea88a9c0dc94b935eafc0ac929038830a6cd31a2ac9f7d"

      def install
        bin.install "track"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/neonxp/track/releases/v0.0.1/track_0.0.1_Linux_x86_64.tar.gz"
      sha256 "1150d8f84ce88600781b7895636b0c53b09d43dbad524e1f192013345069a34d"

      def install
        bin.install "track"
      end
    end
  end
end
